version: '1'
services: 
  # frontend:
  #   build:
  #     context: ./wherebnb-frontend
  #   ports:
  #     - '${FRONTEND_PORT}:3000'
  #   env_file:
  #     - .env
  #  depends_on:
  #     - checkin
  #     - process-booking
  #     - reviews
  #   environment:
  #     - NODE_PORT=${FRONTEND_PORT}

  accoms:
    build:
      context: ./wherebnb-accoms
    env_file:
      - .env
    ports:
      - '8001:${ACCOMS_PORT}'
    environment:
      - NODE_PORT=${ACCOMS_PORT}
      - USE_DB=${USE_DB}
      - REMOTE_DB_TYPE=${REMOTE_DB_TYPE}
      - REMOTE_DB_HOST=${REMOTE_DB_HOST}
      - REMOTE_DB_PORT=${REMOTE_DB_PORT}
      - REMOTE_DB_USER=${REMOTE_DB_USER}
      - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
      - REMOTE_DB_NAME=${REMOTE_DB_NAME}

  bookings:
    build:
      context: ./wherebnb-bookings
    ports:
      - '8002:${BOOKINGS_PORT}'
    env_file:
      - .env
    environment:
      - NODE_PORT=${BOOKINGS_PORT}
      - USE_DB=${USE_DB}
      - REMOTE_DB_TYPE=${REMOTE_DB_TYPE}
      - REMOTE_DB_HOST=${REMOTE_DB_HOST}
      - REMOTE_DB_PORT=${REMOTE_DB_PORT}
      - REMOTE_DB_USER=${REMOTE_DB_USER}
      - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
      - REMOTE_DB_NAME=${REMOTE_DB_NAME}
  
  checkin:
    build:
      context: ./wherebnb-checkin
    ports:
      - '8003:${CHECKIN_PORT}'
    env_file:
      - .env
    environment:
      - NODE_PORT=${CHECKIN_PORT}
      - USE_DB=${USE_DB}
      - REMOTE_DB_TYPE=${REMOTE_DB_TYPE}
      - REMOTE_DB_HOST=${REMOTE_DB_HOST}
      - REMOTE_DB_PORT=${REMOTE_DB_PORT}
      - REMOTE_DB_USER=${REMOTE_DB_USER}
      - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
      - REMOTE_DB_NAME=${REMOTE_DB_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - ACCOMS_URL=${ACCOMS_URL}
      - BOOKINGS_URL=${BOOKINGS_URL}
      - ACCOUNTS_URL=${ACCOUNTS_URL}
      - PROCESS_BOOKING_URL=${PROCESS_BOOKING_URL}
      - PAYMENTS_URL=${PAYMENTS_URL}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_URL}
      - REVIEWS_URL=${REVIEWS_URL}
      - CHECKIN_URL=${CHECKIN_URL}

  reviews:
    build:
      context: ./wherebnb-reviews
    ports:
      - '8004:${REVIEWS_PORT}'
    env_file:
      - .env
    environment:
      - NODE_PORT=${REVIEWS_PORT}
      - USE_DB=${USE_DB}
      - REMOTE_DB_TYPE=${REMOTE_DB_TYPE}
      - REMOTE_DB_HOST=${REMOTE_DB_HOST}
      - REMOTE_DB_PORT=${REMOTE_DB_PORT}
      - REMOTE_DB_USER=${REMOTE_DB_USER}
      - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
      - REMOTE_DB_NAME=${REMOTE_DB_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - ACCOMS_URL=${ACCOMS_URL}
      - BOOKINGS_URL=${BOOKINGS_URL}
      - ACCOUNTS_URL=${ACCOUNTS_URL}
      - PROCESS_BOOKING_URL=${PROCESS_BOOKING_URL}
      - PAYMENTS_URL=${PAYMENTS_URL}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_URL}
      - REVIEWS_URL=${REVIEWS_URL}
      - CHECKIN_URL=${CHECKIN_URL}

  process-booking: #TODO: see if this can connect via NGROK
    build:
      context: ./wherebnb-process-booking
    ports:
      - '8006:${PROCESS_BOOKING_PORT}'
    env_file:
      - .env
    environment:
      - NODE_PORT=${PROCESS_BOOKING_PORT}
      - USE_DB=${USE_DB}
      - REMOTE_DB_TYPE=${REMOTE_DB_TYPE}
      - REMOTE_DB_HOST=${REMOTE_DB_HOST}
      - REMOTE_DB_PORT=${REMOTE_DB_PORT}
      - REMOTE_DB_USER=${REMOTE_DB_USER}
      - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
      - REMOTE_DB_NAME=${REMOTE_DB_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - ACCOMS_URL=${ACCOMS_URL}
      - BOOKINGS_URL=${BOOKINGS_URL}
      - ACCOUNTS_URL=${ACCOUNTS_URL}
      - PROCESS_BOOKING_URL=${PROCESS_BOOKING_URL}
      - PAYMENTS_URL=${PAYMENTS_URL}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_URL}
      - REVIEWS_URL=${REVIEWS_URL}
      - CHECKIN_URL=${CHECKIN_URL}

  notifications: #TODO: verify if this is correct
    build:
      context: ./wherebnb-notifications
    ports:
      - '8005:${NOTIFICATIONS_PORT}'
    env_file:
      - .env
    depends_on:
      - rabbitmq
    environment:
      - NODE_PORT=${NOTIFICATIONS_PORT}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_HOST=${RABBIT_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    # restart: always

  rabbitmq: #TODO: verify if this is correct
    image: 'rabbitmq:3-management'
    env_file:
      - .env
    ports:
      - '5672:${RABBIT_PORT}'
      - '15672:${RABBIT_MANAGEMENT_PORT}'
